name: Tox
on: [push, pull_request]

jobs:
  linting_and_docs:
    runs-on: ubuntu-latest
    name: Linting and Docs
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install third-party tools
        run: |
          sudo apt-get install cmake libenchant-2-dev
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install pandoc
      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.24.2
          cache: true
      - name: Run Task
        env:
          RUFF_OUTPUT_FORMAT: github
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          pixi run ${{ matrix.tox_env }}
      - name: Archive documentation
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: doc/_build/html
        if: ${{ matrix.tox_env == 'build-docs' }}
    strategy:
      fail-fast: false
      matrix:
        tox_env: [lint, build-docs]
